### ISSUE TITLE
Processing text to input (Sign Up)

### ISSUE THREAD

**Issue by MichaelMatros** [MichaelMatros/ByAuthorProjectA#10]
- Write Function to input to remove extra written spaces in the username. 
- Set a limit on the number of characters, make it up to 20

**Comment by mathiasayivor** [comment]
I wouldn't recommend removing extra spaces or modifying usernames in any way. Identification items such as usernames and passwords are very sensitive and unique, and you wouldn't want to modify them for the user. Else users would start complaining about having incorrect username errors

**Comment by MichaelMatros** [comment]
Yes, but it's a username, we can't make it look like this: "@michael   yess rt " . Therefore, I think that it is necessary to forbid writing spaces when entering a username

**Comment by mathiasayivor** [comment]
I get your point now.

**Comment by MichaelMatros** [comment]
Wouldn't it be easier to disable spaces in this field?

**Comment by MichaelMatros** [comment]
And if users are dissatisfied because of this, then we will refer to the private of use where this information will be written, and explained why we should do it this way

**Comment by mathiasayivor** [comment]
It is, but it'd be a good idea to tell the user why we're removing it. Plus, we have to only allow certain characters as username

**Comment by mathiasayivor** [comment]
> And if users are dissatisfied because of this, then we will refer to the private of use where this information will be written, and explained why we should do it this way

🤔 But wouldn't it be better to just show an error at once to the user?

**Comment by MichaelMatros** [comment]
hmm

**Comment by MichaelMatros** [comment]
Then the warning text will be large enough

**Comment by MichaelMatros** [comment]
can try to make a pop-up warning when entering an input. I'll think of a better way to do it and let you know

**Comment by mathiasayivor** [comment]
Right. But we can just utilize the existing warning field :man_shrugging:

**Comment by MichaelMatros** [comment]
Yes, but then it doesn't look good because you have to add another sentence to the warning message. It seems to me much easier to just prohibit the space and that's it)

**Comment by MichaelMatros** [comment]
We are only "interfered" with a space, the rest of the characters are available. Users can use for example,  underscore
