### ISSUE TITLE
The form of the error in the 1st step of registration has changed

### ISSUE THREAD

**Issue by MichaelMatros** [MichaelMatros/ByAuthorProjectA#12]
Please note that the forms of warnings in the registration form of the first step and the registration form of the second step are different

**Comment by mathiasayivor** [comment]
Can you explain further?

**Comment by MichaelMatros** [comment]
Error form in the first step of the registration form

![image 94](https://user-images.githubusercontent.com/60701432/224487197-f586fdf7-6117-4d3e-a984-71a4aa5c94a9.png)

**Comment by MichaelMatros** [comment]
Error form in the second step of the registration form
![image](https://user-images.githubusercontent.com/60701432/224487250-9e910bda-5128-49fa-9075-d31286953277.png)

**Comment by mathiasayivor** [comment]
Check the form. It works exactly the same.

**Comment by MichaelMatros** [comment]
No 

![image](https://user-images.githubusercontent.com/60701432/224488340-a13ad8e0-73c0-4172-a747-d0ad1f4d2d41.png)

**Comment by mathiasayivor** [comment]
![Screenshot from 2023-03-15 22-14-32](https://user-images.githubusercontent.com/74247733/225455795-50e6808c-6012-4c83-96dc-289dc1ec47d1.png)
![Screenshot from 2023-03-15 22-14-52](https://user-images.githubusercontent.com/74247733/225455805-5ad870fd-033c-4cc5-bd6f-64bd938b3136.png)

**Comment by MichaelMatros** [comment]
In the first picture, the error warning looks wrong

**Comment by mathiasayivor** [comment]
What's the expected error?

**Comment by mathiasayivor** [comment]
In the figma file, screenshot, its: "Check the correctness of the *email*, *username*, password"
In the real version, its: "Check the correctness of *Username*, *Email*, *Password*, *Confirm Password*"

What am I getting wrong?

**Comment by mathiasayivor** [comment]
Perhaps its the "the" before *email*? or the way the fields are capitalised?

**Comment by MichaelMatros** [comment]
No no, I'm not talking about the text, I pay attention to the color + icon between the line and the text

**Comment by mathiasayivor** [comment]
So, the first message should show a red colour with icon, but the second step should just hide it and show error text only?

**Comment by mathiasayivor** [comment]
That's a bit inconsistent imo, but sure. I can make it work as you wish.

**Comment by MichaelMatros** [comment]
Yes, that's right, the first with an icon and red, the second without an icon and black
