### ISSUE TITLE
Add input confirmation with enter

### ISSUE THREAD

**Issue by MichaelMatros** [MichaelMatros/ByAuthorProjectA#13]

**Comment by mathiasayivor** [comment]
@MichaelMatros can you further explain this?

**Comment by MichaelMatros** [comment]
Make it possible to confirm input using the keyboard - the "enter" button

**Comment by mathiasayivor** [comment]
Sorry, but I still don't get what you mean

**Comment by MichaelMatros** [comment]
ohh well, the user enters his data into the input, he finished entering the text, and wants to move on to the next input, he will be able to press enter on the keyboard, thereby confirming the input of information, thereby moving to the next input

**Comment by mathiasayivor** [comment]
> ohh well, the user enters his data into the input, he finished entering the text, and wants to move on to the next input, he will be able to press enter on the keyboard, thereby confirming the input of information, thereby moving to the next input

This would change the expected behaviour when enter is pressed for input fields. And I wouldn't recommend.

**Comment by MichaelMatros** [comment]
tabs? No one seems to use tabs, I always use the enter key everywhere when registering on a website or when logging in, the enter is more convenient and everyone knows about it, it seems to me

**Comment by mathiasayivor** [comment]
If you're referring to moving to the next step with Enter, it works. But moving to the next input field in the same step with Enter? The Enter key is supposed to submit the form.

**Comment by mathiasayivor** [comment]
No probs. Would make it move to next input field when Enter is pressed.

**Comment by MichaelMatros** [comment]
yup
